name: lightning_savanna_shardagent

trainer_params:
  resume_from_checkpoint: False
  num_workers: 14
  max_epochs: 200
  record_path: "../checkpoints/memory_records/test2.csv"
  device: "cuda"

hparams:
  batch_size: 16
  lr: 0.001
  env: "savanna-gym-v2"
  env_entry_point: "aintelope.environments.savanna_gym:SavannaGymEnv"
  env_type: "gym"
  model: "dqn"
  agent: shard_agent
  gamma: 0.99
  sync_rate: 10
  replay_size: 99
  warm_start_size: 100
  eps_last_frame: 1000
  eps_start: 1.0
  eps_end: 0.01
  episode_length: 1010
  warm_start_steps: 100
  env_params:
    num_iters: 1000 # duration of the game
    map_min: 0
    map_max: 5
    render_map_max: 5
    amount_agents: 1 # for now only one agent
    amount_grass_patches: 2
    amount_water_holes: 2
  agent_params:
    target_shards: ["hunger", "thirst", "curiosity"]
